### ISSUE TITLE
copy URL cissors multiplication

### ISSUE THREAD

**Issue by matt-regnier** [matt-regnier/Gitoma#10]

**Comment by matt-regnier** [comment]
<img width="1680" alt="screen shot 2018-06-25 at 11 08 17 pm" src="https://user-images.githubusercontent.com/8615814/41875965-b714a6d6-78cc-11e8-9318-1745ff4f6cc9.png">

**Comment by matt-regnier** [comment]
this happen when you right after you click on submit... after creating an issue.

**Comment by waelabd** [comment]
it should be corrected with the next version. There will be still a delay for the scissors to appear.

**Comment by matt-regnier** [comment]
delay is fine :)
