### ISSUE TITLE
create a new issue in a new windows: the header desepear. 

### ISSUE THREAD

**Issue by matt-regnier** [matt-regnier/Gitoma#12]
<img width="1192" alt="screen shot 2018-06-25 at 11 12 24 pm" src="https://user-images.githubusercontent.com/8615814/41876157-3af37946-78cd-11e8-88ca-387e172772bc.png">

**Comment by waelabd** [comment]
it should be corrected with the new version, reopen if needed.

**Comment by matt-regnier** [comment]
ok let me know @waeldgm

**Comment by waelabd** [comment]
I close it, it is not relevant in current version.
