### ISSUE TITLE
Google links -> need to be open in chrome / not in gitoma

### ISSUE THREAD

**Issue by matt-regnier** [matt-regnier/Gitoma#14]
<img width="1212" alt="screen shot 2018-06-28 at 2 27 56 pm" src="https://user-images.githubusercontent.com/8615814/42034316-f1a6178e-7adf-11e8-9dbf-d991b84f1722.png">

**Comment by waelabd** [comment]
@matt-regnier can you tell from which link you've got this error?

I think it comes from the bug you've mention #12

**Comment by waelabd** [comment]
@matt-regnier

**Comment by matt-regnier** [comment]
n'importe quelle lien google docs Ex : https://github.com/dagoma3d/client/issues/102

**Comment by waelabd** [comment]
Je comprend pas.. Il s'ouvre à l'intérieur pq c'est pas un lien google.

Lui s'ouvre à l'extérieur:

https://www.google.fr/search?q=google&oq=google&aqs=chrome..69i57j69i60l3j0j69i65.4199j0j7&sourceid=chrome&ie=UTF-8

**Comment by waelabd** [comment]
@Gitoma-wovico

**Comment by waelabd** [comment]
Fixed with 2.0.7
