### ISSUE TITLE
add button "new milestone" on the top

### ISSUE THREAD

**Issue by matt-regnier** [matt-regnier/Gitoma#2]

**Comment by waelabd** [comment]
Do you really need that finally?

We could do something like that? The + next to the milestone.
<img width="1183" alt="capture d ecran 2018-06-26 a 08 48 32" src="https://user-images.githubusercontent.com/37664122/41894044-f233fc48-791d-11e8-8acd-cbcbfe8fd9c7.png">

**Comment by matt-regnier** [comment]
non / je clos.
