### ISSUE TITLE
Can't "choose for Gitoma"

### ISSUE THREAD

**Issue by thedamfr** [matt-regnier/Gitoma#20]
![capture d ecran 2018-09-11 a 17 01 50](https://user-images.githubusercontent.com/2880446/45368656-6404b080-b5e4-11e8-9c8c-3422f95fd2f9.png)

I can scroll to the bottom without finding the good repository !
Too many of them ? 🙂

**Comment by matt-regnier** [comment]
@thedamfr merci !!

**Comment by waelabd** [comment]
Fix with 2.0.7 not need to choose anymore
