### ISSUE TITLE
New window size: need to be bigger

### ISSUE THREAD

**Issue by matt-regnier** [matt-regnier/Gitoma#3]
when you open a new windows (cmd+click)

**Comment by matt-regnier** [comment]
as we describe it in the specs : https://docs.google.com/document/d/1-K2w44d-ReIkIwGVOyvFsw76dfSUr6zC86xIOFK40AU/edit

**Comment by matt-regnier** [comment]
<img width="1172" alt="screen shot 2018-06-30 at 10 56 37 am" src="https://user-images.githubusercontent.com/8615814/42123550-4d514886-7c54-11e8-8a91-dabade7378e5.png">

**Comment by matt-regnier** [comment]
it's also important to add them strait / look on this picture : 
 - there is files / shoud be. 
 - but there is no refresh :) 

<img width="1212" alt="screen shot 2018-06-30 at 10 57 08 am" src="https://user-images.githubusercontent.com/8615814/42123560-65741f74-7c54-11e8-94ec-b9d022dd5a47.png">

**Comment by waelabd** [comment]
It should be corrected with the next version.
